"""empty message

Revision ID: 0d66e7b5c2e4
Revises: 308cc2cf834b
Create Date: 2017-10-08 04:52:37.378133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d66e7b5c2e4'
down_revision = '308cc2cf834b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('_default_scopes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client', '_default_scopes')
    # ### end Alembic commands ###
